version: '2'
services:
  dev:
    image: node:10-alpine
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: ./node_modules/nodemon/bin/nodemon.js /usr/src/app
    ports:
      - 3010:3000
